<?xml version="1.0"?>
<package format="3">
  <name>buildscan_industrial_demo</name>
  <version>1.0.0</version>
  <description>BuildScan Rover - buildscan_industrial_demo package</description>
  <maintainer email="buildscan@example.com">BuildScan Team</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclpy</depend>
  <depend>buildscan_interfaces</depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
