cmake_minimum_required(VERSION 3.8)
project(buildscan_description)
find_package(ament_cmake REQUIRED)
install(DIRECTORY launch/ DESTINATION share/${PROJECT_NAME}/launch OPTIONAL)
install(DIRECTORY config/ DESTINATION share/${PROJECT_NAME}/config OPTIONAL)
install(DIRECTORY worlds/ DESTINATION share/${PROJECT_NAME}/worlds OPTIONAL)
install(DIRECTORY urdf/   DESTINATION share/${PROJECT_NAME}/urdf   OPTIONAL)
install(DIRECTORY rviz/   DESTINATION share/${PROJECT_NAME}/rviz   OPTIONAL)
ament_package()
